1. Introduction

Definition:
PyTorch is an open-source deep learning framework developed by Facebook AI Research (FAIR) used for building and training neural networks. It provides dynamic computation graphs, which allow flexibility for research and debugging.

Key Points for Interview:

Pythonic and easy to debug.

Supports GPU acceleration using CUDA.

Used widely in research and production.

Main alternatives: TensorFlow, JAX.

Dynamic vs Static Graphs:

Dynamic Graph (PyTorch): Built on-the-fly during execution. Good for flexible architectures (like RNNs).

Static Graph (TensorFlow 1.x): Defined before execution, optimized but less flexible

In [ ]:
pip install torch

In [ ]:
import torch


# Check PyTorch version
print(torch.__version__)

# Check if CUDA is available
print(torch.cuda.is_available())



2.8.0+cu126
True


2. PyTorch Basics: Tensors

Definition:

A Tensor is a multi-dimensional array similar to NumPy arrays, but can run on GPU for faster computation. Tensors are the building blocks of PyTorch.

Types of Tensors:

1D Tensor → Vector

2D Tensor → Matrix

3D Tensor or higher → For images, videos, etc.

Key Operations:

Creation: torch.tensor(), torch.zeros(), torch.ones(), torch.rand()

GPU support: .to('cuda') or .cuda()

In [ ]:
# 1D Tensor
a=torch.tensor([1,2,3,4])
print(a,a.shape)

tensor([1, 2, 3, 4]) torch.Size([4])


In [ ]:
#2D Tensor
b=torch.ones(4,3)
print(b,b.shape)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]) torch.Size([4, 3])


In [ ]:
#Random Tensor :Creates a tensor with random numbers uniformly distributed between [0, 1).

c=torch.rand(7,3) #row*column
print(c,c.shape)

tensor([[0.7937, 0.0619, 0.7697],
        [0.2627, 0.3267, 0.3768],
        [0.2833, 0.9035, 0.9430],
        [0.7242, 0.9096, 0.8083],
        [0.6107, 0.1688, 0.8283],
        [0.9123, 0.4858, 0.6911],
        [0.6971, 0.1808, 0.7716]]) torch.Size([7, 3])


In [ ]:
#  Move tensor to GPU (if available)
if torch.cuda.is_available():
  c = c.to('cuda')
  print(c)



tensor([[0.7937, 0.0619, 0.7697],
        [0.2627, 0.3267, 0.3768],
        [0.2833, 0.9035, 0.9430],
        [0.7242, 0.9096, 0.8083],
        [0.6107, 0.1688, 0.8283],
        [0.9123, 0.4858, 0.6911],
        [0.6971, 0.1808, 0.7716]], device='cuda:0')


In [ ]:
d=torch.zeros([5,3])
print(d)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [ ]:
# Creates a 1D tensor with values starting from a start value, incrementing by a step, and stopping before the end value.torch.arange(start, end, step)

arange = torch.arange(0, 20, 1)
print(arange)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19])


In [ ]:
# Creates a 1D tensor with evenly spaced numbers between a start and end value, including both ends.📏 Use arange for steps, and linspace for equal intervals.
linspace = torch.linspace(0, 1, 7)

print(linspace)

tensor([0.0000, 0.1667, 0.3333, 0.5000, 0.6667, 0.8333, 1.0000])


In [ ]:
# From Existing Data
data=[[1,2,3,4]]
tensor_from_list = torch.tensor(data)
print(tensor_from_list)

tensor([[1, 2, 3, 4]])


In [ ]:
import numpy as np

np_array = np.array([[1,2,3],[4,5,6]])
tensor_from_np = torch.from_numpy(np_array)
print(tensor_from_np)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [ ]:
# Tensor Attributes (Inspecting Tensor)
# Tensors have attributes that describe their structure.        -----------important

tensor = torch.rand(1,2)
print(tensor)

print(tensor.shape)

print(tensor.ndimension())
print(tensor.dtype)
print(tensor.device)     # cpu or cuda

tensor([[0.0679, 0.5195]])
torch.Size([1, 2])
2
torch.float32
cpu


In [ ]:
print(torch.cuda.get_device_name(0))


Tesla T4


In [ ]:
device = "cuda" if torch.cuda.is_available() else "cpu".          #important ---------------------
print(device)

# Tensor on GPU (for speed)
device = "cuda" if torch.cuda.is_available() else "cpu"
tensor = torch.rand(2, 3).to(device)
print(tensor.device)



x=torch.tensor([1,2,3])
device= "cuda" if torch.cuda.is_available() else "cpu"
x=torch.tensor([1,2,3])
print(x.to(device))
print(x.cuda())


print(torch.cuda.device_count())
print(torch.cuda.current_device())
print(torch.cuda.get_device_name(0))
print(torch.cuda.memory_allocated(0))

cuda
cuda:0
tensor([1, 2, 3], device='cuda:0')
tensor([1, 2, 3], device='cuda:0')
1
0
Tesla T4
512


In [ ]:
# Element-wise Operations
x=torch.tensor([1,2,3])
y=torch.tensor([4,5,6])
a=x+y
print(a)
b=x-y
print(b)
c=x*y
print(c)
d=x/y
print(d)

tensor([5, 7, 9])
tensor([-3, -3, -3])
tensor([ 4, 10, 18])
tensor([0.2500, 0.4000, 0.5000])


In [ ]:
# ➤ Matrix Operations
a=torch.tensor([[1,2],[3,4]])
b=torch.tensor([[5,6],[7,8]])
# print(a)
# print(b)
print(torch.matmul(a,b))
print(a @ b)
print(torch.cuda.device_count())
print(torch.cuda.current_device())
print(torch.cuda.get_device_name(0))
             # Shortcut


tensor([[19, 22],
        [43, 50]])
tensor([[19, 22],
        [43, 50]])
1
0
Tesla T4


In [ ]:
# Reshaping and Transposing
x = torch.arange(1, 12)
print(x)
x_reshaped = x.view(11, 1)
print(x_reshaped)   # Reshape
x_transpose = x_reshaped.t() # Transpose
print(x_transpose)


tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
tensor([[ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11]])
tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])


In [ ]:
# ➤ Slicing and Indexing
x = torch.arange(1, 10).view(3,3)
print(x)
print(x[0])       # First row
print(x[:, 1]) # Second column
print(x[1:,])   # Second row
print(x[1, 1])    # Element at (1,1)





tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([1, 2, 3])
tensor([2, 5, 8])
tensor([[4, 5, 6],
        [7, 8, 9]])
tensor(5)


In [ ]:
# Broadcasting automatically expands smaller tensors to match larger tensor shapes during operations, without physically copying data.
import torch

a = torch.ones((3, 3))
b = torch.tensor([1, 2, 4])  # shape (3,)
c = a + b
print(c)

tensor([[2., 3., 5.],
        [2., 3., 5.],
        [2., 3., 5.]])


In [ ]:
# In-place operations directly modify tensor data without creating a new copy.
x = torch.tensor([1, 2, 3])
x.add_(2)
print(x)


tensor([3, 4, 5])


In [ ]:
# 🔹 3️⃣ Concatenation & Stacking
# Concatenation (torch.cat):

# Joins tensors along an existing dimension.
a = torch.tensor([[1, 2], [3, 4]])
b = torch.tensor([[5, 6]])
cat = torch.cat((a, b), dim=0)
print(cat)
print(cat.shape)

tensor([[1, 2],
        [3, 4],
        [5, 6]])
torch.Size([3, 2])


In [ ]:
# Stacking (torch.stack)
# Stacking combines tensors along a new dimension, unlike torch.cat which joins along an existing dimension.
# Adds a new dimension while combining tensors.
x = torch.tensor([1, 2])
y = torch.tensor([3, 4])
stacked = torch.stack((x, y))
print(stacked)
print(stacked.shape)

tensor([[1, 2],
        [3, 4]])
torch.Size([2, 2])


In [ ]:
import torch

a = torch.tensor([1, 2])
b = torch.tensor([3, 4])
c = torch.tensor([5, 6])

stack0 = torch.stack((a, b, c), dim=0)  # stack along new first dimension
stack1 = torch.stack((a, b, c), dim=1)  # stack along new second dimension

print("dim=0:", stack0)
print("dim=0 shape:", stack0.shape)
print("--------------")
print("dim=1:", stack1)
print("dim=1 shape:", stack1.shape)

dim=0: tensor([[1, 2],
        [3, 4],
        [5, 6]])
dim=0 shape: torch.Size([3, 2])
--------------
dim=1: tensor([[1, 3, 5],
        [2, 4, 6]])
dim=1 shape: torch.Size([2, 3])


In [ ]:
# unsqueeze(dim) → adds a new dimension

# cat() → concatenates along that dimension

# Output is identical to torch.stack((x, y, z), dim=0)

# This helps understand stacking as a combination of unsqueeze + concat.
x = torch.tensor([1,2])
y = torch.tensor([3,4])
z = torch.tensor([5,6])

stack_manual = torch.cat((x.unsqueeze(0), y.unsqueeze(0), z.unsqueeze(0)), dim=0)
print(stack_manual)

tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [ ]:
# torch.hstack and torch.vstack (specialized stacking)

# torch.vstack → stack along rows (vertical, dim=0 for 2D)

# torch.hstack → stack along columns (horizontal, dim=1 for 2D)


a = torch.tensor([[1,2]])
b = torch.tensor([[3,4]])

v = torch.vstack((a,b))
h = torch.hstack((a,b))

print("vstack:", v)
print("hstack:", h)

vstack: tensor([[1, 2],
        [3, 4]])
hstack: tensor([[1, 2, 3, 4]])


In [ ]:
# Cloning vs Detaching

# clone()

# Creates a copy of tensor with the gradient tracking.

x = torch.tensor([1,2,3.], requires_grad=True)
y = x.clone()
print(y.requires_grad)  # True
y

True


tensor([1., 2., 3.], grad_fn=<CloneBackward0>)

In [ ]:
# detach()

# Creates a new tensor without tracking gradients (used in inference).✅ Use .detach() when you want a tensor but don’t want autograd to follow it.

y = x.detach()
print(y.requires_grad)  # False

False


In [ ]:
# Type Casting & Device Movement
# Data type conversion
x = torch.tensor([1, 2, 3])
print(x.float())   # Convert to float32
print(x.double())  # Convert to float64
print(x.int())     # Convert to int32

tensor([1., 2., 3.])
tensor([1., 2., 3.], dtype=torch.float64)
tensor([1, 2, 3], dtype=torch.int32)


In [ ]:
# eduction Operations (Summarizing Data)
# Sum, Mean, Max, etc.

# Use dim to control which axis to reduce:

# dim=0 → column-wise

# dim=1 → row-wise
x = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])
x=x.float()

print(x.sum())       # All elements
print(x.mean(dim=0)) # Column-wise mean
print(x.max(dim=1))  # Row-wise max + indices

tensor(21.)
tensor([2.5000, 3.5000, 4.5000])
torch.return_types.max(
values=tensor([3., 6.]),
indices=tensor([2, 2]))


In [ ]:
# Comparison Operations
x = torch.tensor([1, 2, 3])
y = torch.tensor([2, 2, 2])

print(x == y)   # element-wise equality
print(x > y)    # greater than
print(torch.equal(x, y))  # all elements equal?

tensor([False,  True, False])
tensor([False, False,  True])
False


In [ ]:
x = torch.tensor([[1, 2, 3]])
print(x.unsqueeze(0).shape)  # (1,1,3)
print(x.squeeze().shape)

torch.Size([1, 1, 3])
torch.Size([3])


In [ ]:
# squeeze()

# Definition:
# Removes dimensions of size 1 from a tensor.

# Purpose:

# Helps simplify tensor shapes.

# Common in CNNs to remove extra singleton dimensions after convolution or pooling.


x = torch.randn(1, 3, 1, 4)
y = x.squeeze()  # removes all dimensions with size 1
print(y.shape)   # torch.Size([3, 4])

# Remove specific dimension
z = x.squeeze(0)  # remove only dim 0
print(z.shape)    # torch.Size([3, 1, 4])


torch.Size([3, 4])
torch.Size([3, 1, 4])


In [ ]:
# unsqueeze()

# Definition:
# Adds a dimension of size 1 at the specified position.     squeeze and unsqueeze are commonly used together to align shapes for neural networks.

# Purpose:

# Useful to match input shapes for broadcasting.

# Often used in CNNs/RNNs to add batch or channel dimensions.


x = torch.tensor([1,2,3])       # shape (3)
y = x.unsqueeze(0)               # add batch dim at 0 → (1,3)
z = x.unsqueeze(1)               # add dim at 1 → (3,1)


In [ ]:
# permute()

# Definition:
# Reorders dimensions of a tensor according to the given order.

# Purpose:

# Often used to convert between tensor layouts, e.g., (H, W, C) ↔ (C, H, W) for image processing.

# Does not change data, just changes how dimensions are viewed.


x = torch.randn(2, 3, 4)   # shape (2,3,4)
y = x.permute(1, 0, 2)     # shape (3,2,4)

In [ ]:
# Rank / Order

# Definition: Number of dimensions a tensor has.
# Purpose: Identifies if it’s a scalar (0D), vector (1D), matrix (2D), or higher.

# Example:

scalar = torch.tensor(5)          # 0D
vector = torch.tensor([1, 2, 3])  # 1D
matrix = torch.tensor([[1,2],[3,4]]) # 2D
print(scalar.ndim)  # Output: 0 1 2
print(vector.ndim)
print(matrix.ndim)
print(scalar.shape,vector.shape,matrix.shape)



0
1
2
torch.Size([]) torch.Size([3]) torch.Size([2, 2])


In [ ]:
# Static vs Dynamic Computation Graphs

# Static Graphs (e.g., TensorFlow 1.x):
# You must define the entire computation before running it (like a fixed blueprint).

# Dynamic Graphs (PyTorch):
# The graph is built on the fly as operations are executed — perfect for debugging and variable-length inputs.


# derivative
x = torch.tensor(2.0, requires_grad=True)
y = x**2 + 3*x + 2
y.backward()
print(x.grad)  # derivative = 2x + 3 → 2*2 + 3 = 7


tensor(7.)
